version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true

  backend:
    build: ./backend
    container_name: backend
    environment:
      JWT_SECRET: "VERY_SECRET_VALUE"
      DATABASE_URL: "postgresql://postgres:postgres@localhost:6000/chuck-norris-db?schema=public"
    ports:
      - "4000:4000"
    stdin_open: true

  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chuck-norris-db
    ports:
      - "6000:6000"
