version: "3.8"
services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - "./backend/.env"
    ports:
      - "5444:5432"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    stdin_open: true

  backend:
    build: ./backend
    container_name: backend
    restart: "on-failure"
    env_file:
      - "./backend/.env"
    ports:
      - "4000:4000"
    stdin_open: true
    depends_on:
      - database
